Connected to Python 3.12.10

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("../../data/homicideos.csv")

FileNotFoundError: [Errno 2] No such file or directory: '../../data/homicideos.csv'

In [ ]:
df = pd.read_csv("../../data/homicidios.csv")

FileNotFoundError: [Errno 2] No such file or directory: '../../data/homicidios.csv'

In [ ]:
df = pd.read_csv("../../data/homicidios.csv", sep = ";")

FileNotFoundError: [Errno 2] No such file or directory: '../../data/homicidios.csv'

In [ ]:
df = pd.read_csv("../../data/homicidios.csv", sep = ";")

FileNotFoundError: [Errno 2] No such file or directory: '../../data/homicidios.csv'

In [ ]:
df = pd.read_csv("../../data/homicidios", sep = ";")

FileNotFoundError: [Errno 2] No such file or directory: '../../data/homicidios'

In [ ]:
df = pd.read_csv("../../data/homicidios.csv", sep = ";")

FileNotFoundError: [Errno 2] No such file or directory: '../../data/homicidios.csv'

In [ ]:
df = pd.read_csv("../../data/homicidios-homens.csv", sep = ";")

FileNotFoundError: [Errno 2] No such file or directory: '../../data/homicidios-homens.csv'

In [ ]:
df = pd.read_csv("../../data/homicidios.csv", sep = ";")

FileNotFoundError: [Errno 2] No such file or directory: '../../data/homicidios.csv'

In [ ]:
df = pd.read_csv("../data/homicidios.csv", sep = ";")

In [ ]:
df

     cod nome  período  valor
0     53   DF     1989    331
1     11   RO     1989    490
2     12   AC     1989     95
3     13   AM     1989    321
4     14   RR     1989    113
..   ...  ...      ...    ...
886   23   CE     2021   3471
887   22   PI     2021    766
888   21   MA     2021   1999
889   17   TO     2021    441
890   53   DF     2021    401

[891 rows x 4 columns]

In [ ]:
df.shape

(891, 4)

In [ ]:
df = df.rename(columns = ("valor": "homicideos" ))

SyntaxError: invalid syntax (<ipython-input-13-732b86d62788>, line 2)

In [ ]:
df_geral = df.rename(columns = {"valor": "homicideos"})

In [ ]:
df_geral = df.rename(columns = {"valor": "homicideos"})
df_geral.head()

   cod nome  período  homicideos
0   53   DF     1989         331
1   11   RO     1989         490
2   12   AC     1989          95
3   13   AM     1989         321
4   14   RR     1989         113

In [ ]:
df_negros = pd.read_csv("../data/homicidios-negros.csv", sep = ";")

In [ ]:
df_negros = pd.read_csv("../data/homicidios-negros.csv", sep = ";")
df_negros.head()

   cod nome  período  valor
0   12   AC     1996      0
1   17   TO     1996      0
2   35   SP     1996    359
3   28   SE     1996      0
4   42   SC     1996      0

In [ ]:
df_negros = pd.read_csv("../data/homicidios-negros.csv", sep = ";")
df_negros = df_negros.rename(columns = {"valor": "homicideos.negros"})
df_negros.head()

   cod nome  período  homicideos.negros
0   12   AC     1996                  0
1   17   TO     1996                  0
2   35   SP     1996                359
3   28   SE     1996                  0
4   42   SC     1996                  0

In [ ]:
df_geral.set_index(["nome, "periodo])

concat.pd

SyntaxError: invalid syntax. Perhaps you forgot a comma? (<ipython-input-19-930559efc750>, line 3)

In [ ]:
df_geral.set_index(["nome", "periodo"])

concat.pd

KeyError: "None of ['periodo'] are in the columns"

In [ ]:
df_geral.set_index(["nome", "período"])

concat.pd

NameError: name 'concat' is not defined

In [ ]:
df_geral.set_index(["nome", "período"])

              cod  homicideos
nome período
DF   1989      53         331
RO   1989      11         490
AC   1989      12          95
AM   1989      13         321
RR   1989      14         113
...           ...         ...
CE   2021      23        3471
PI   2021      22         766
MA   2021      21        1999
TO   2021      17         441
DF   2021      53         401

[891 rows x 2 columns]

In [ ]:
df_geral.set_index(["nome", "período"])
df_negros.set_index(["nome", "período"])

              cod  homicideos.negros
nome período
AC   1996      12                  0
TO   1996      17                  0
SP   1996      35                359
SE   1996      28                  0
SC   1996      42                  0
...           ...                ...
PA   2021      15               2611
MT   2021      51                672
MS   2021      50                388
RS   2021      43                456
SC   2021      42                172

[702 rows x 2 columns]

In [ ]:
pd.concat([df_geral, df_negros])

     cod nome  período  homicideos  homicideos.negros
0     53   DF     1989       331.0                NaN
1     11   RO     1989       490.0                NaN
2     12   AC     1989        95.0                NaN
3     13   AM     1989       321.0                NaN
4     14   RR     1989       113.0                NaN
..   ...  ...      ...         ...                ...
697   15   PA     2021         NaN             2611.0
698   51   MT     2021         NaN              672.0
699   50   MS     2021         NaN              388.0
700   43   RS     2021         NaN              456.0
701   42   SC     2021         NaN              172.0

[1593 rows x 5 columns]

In [ ]:
pd.concat([df_geral, df_negros], axis = 1)

     cod nome  período  homicideos   cod nome  período  homicideos.negros
0     53   DF     1989         331  12.0   AC   1996.0                0.0
1     11   RO     1989         490  17.0   TO   1996.0                0.0
2     12   AC     1989          95  35.0   SP   1996.0              359.0
3     13   AM     1989         321  28.0   SE   1996.0                0.0
4     14   RR     1989         113  42.0   SC   1996.0                0.0
..   ...  ...      ...         ...   ...  ...      ...                ...
886   23   CE     2021        3471   NaN  NaN      NaN                NaN
887   22   PI     2021         766   NaN  NaN      NaN                NaN
888   21   MA     2021        1999   NaN  NaN      NaN                NaN
889   17   TO     2021         441   NaN  NaN      NaN                NaN
890   53   DF     2021         401   NaN  NaN      NaN                NaN

[891 rows x 8 columns]

No kernel connected